# Generated by Django 2.0.7 on 2018-07-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='person',
        ),
        migrations.RemoveField(
            model_name='group',
            name='person',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='person',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
