# Generated by Django 2.0.7 on 2018-07-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0002_auto_20180716_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('phone_type', models.CharField(choices=[('1', 'private'), ('2', 'office')], default=1, max_length=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories.Person')),
            ],
        ),
    ]
