# Generated by Django 2.0.7 on 2018-07-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0003_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('email_type', models.CharField(choices=[('1', 'private'), ('2', 'office')], default=1, max_length=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories.Person')),
            ],
        ),
    ]
