# Generated by Django 2.0.7 on 2018-07-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0004_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('1', 'Favourite'), ('2', 'Family'), ('3', 'Work'), ('4', 'Other')], default=1, max_length=1)),
                ('person', models.ManyToManyField(to='user_stories.Person')),
            ],
        ),
    ]
